name: DevSecOps Pipeline

# Trigger: Jalan setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  # TAHAP 1: KEAMANAN (CI)
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Scan File System (Mencari miskonfigurasi/secret bocor)
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          severity: 'CRITICAL,HIGH'
          exit-code: 1 # Gagada isu Critical

  # TAHAP 2: DEPLOYMENT (CD)
  deploy:
  needs: security-check
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/learngoad
          git pull origin main
          docker restart my-website-container
          docker ps
