name: DevSecOps Pipeline

# Trigger: Jalan setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  # TAHAP 1: KEAMANAN (CI)
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Scan File System (Mencari miskonfigurasi/secret bocor)
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          severity: 'CRITICAL,HIGH'
          exit-code: 1 # Gagal jika ada isu Critical

  # TAHAP 2: DEPLOYMENT (CD)
  deploy:
    needs: security-check # Hanya jalan jika security-check SUKSES
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder project di server
            cd /mnt/z/learngoad/learngoad-main
            
            # Tarik kode terbaru dari GitHub
            git pull origin main
            
            # Restart Container (Contoh: Nginx/Web Server)
            # Sesuaikan nama container kamu
            docker restart my-website-container
            
            # Cek status container setelah restart
            docker ps
